# Generated by Django 5.2 on 2025-04-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_alice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
